### ISSUE TITLE
Small feedback

### ISSUE THREAD

**Issue by kamilfedio** [Mabuza713/BrainTumorDetection#1]
Hi, I would like to share my notes. Firstly use poetry or some another package manager since installing packages can be terrible. Whats more with package manager you can set version for library so in future you won't have any problems with compatibility. Functions in classes you should write with lowercases and use snake case
Except that you can create config file for all params user can change and can be useful. It terrible to change something in every file :D. And last idea - create .env file with e.g. paths for images etc. It very useful. If you find it helpful let me know if i helped you

**Comment by kamilfedio** [comment]
I find one more thing - it's bad idea to place data like images in github imo. You can place them in some cloud on download them by api for training. It only my view for this

**Comment by Mabuza713** [comment]
I will implement these suggestions when i'll have some more free time. Thank you so much for valuable feedback!
